# Generated by Django 4.0 on 2022-10-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('file', models.FileField(upload_to='resumes/')),
                ('processed_resume', models.CharField(max_length=5000)),
                ('status', models.CharField(default='under_consideration', max_length=50)),
            ],
        ),
    ]
